In [1]:
from PyPDF2 import PdfReader

reader = PdfReader("../T_1.pdf")
number_of_pages = len(reader.pages)
page = reader.pages[0]
text = page.extract_text()
print(text)

TRAIN NAMEDelhiAlipur-duar Jn. SikkimMahan-andaExpressKalkaHowrahNetajiEx-pressBarm-erHow-rahEx-pressNewDelhiRajgirShram-jeeviExpressNewDelhiGayaMa-habodhiEx-pressAnandVihar (T) Ka-makhyaNorthEast Ex-pressAnandVihar (T) Bhagal-purVikram ShilaExpressAnandVihar (T) DanapurJanSad-haranExpressAnandVihar (T)GayaGaribrath Ex-pressAnandVihar (T)HaldiaEx-pressPrayagRaj Ram-baghHowrahVib huti ExpressBikanerPrayag-rajExpressBikanerPrayag-rajExpressPatnaKol-kataGaribRathEx-pressVeerangna Laxmi Bai  KolkataPrathamSwatantrataSangramExpressKanpurPrayagrajsangamExpressPatnaShali-marDuron-toEx-pressGhazi-purcityKolkataExpress (ViaPatna)AnandVihar (T Prayag-rajHum-safarExpressAnandVihar (T) Mad-hupurHum-safarExpressAnandVihar (T) MadhupurBaba Vaidy-anath Dham DeogharExpressMoka-maHow-rahEx-pressJasi-dih-SM-VTBengal-uru Ex-pressTrain Number 15484 12312 12324 12392 12398 12506 12368 13258 22410 12444 12334 12404 20404 12360 22198 14102 22214 13122 22438 22460 22466 13030 22306 Class of accommodation 2A,3A SL,II,P1A,2A,3A SL,II,P2A,3A SL,II1A,2A,3A,SL,II,P2A,3A SL,II,P2A,3A SL,II,P1A,2A,3A SL,II,PII 3A 3A,SL, II2A,3A SL,II1A,2A,3A, 3E, SL,II1A,2A,3A, 3E, SL,II3A 2A, 3A, SL,II II 1A,2A, 3A SL2A, 3A, SL, II3A, SL 3A, SL 2A,3A, SL,II SL,II
1A, 2A, 3A,SL,II,P
From Table No. 27A 59A via 25 80 80 35A 22 Days of departure atoriginating station Daily Daily W,Sa Daily Daily Daily Daily Daily Sa Tu Daily Tu,W,F,-SuM,Th,SaSu,W,FF DailyTu,Th, SaMTu,Th, SuM W Daily FKm.
Delhiad07.3506.0007.1507.3007.55
New Delhiad13.10 12.50
13 Anand Vihar (T) d 07.40 13.15 13.35 20.20 20.20 22.35 12.45 12.45
25 Ghaziabad d 08.16 07.00 ... 13.51 ... ... ... 20.47 20.4795 Khurja d 09.05 07.58126 Aligarh d 09.50 08.35 ... 14.30 09.13 ... ...145
Mathura d 19.5019.5519.5019.55 199 Agra Cantt. d 21.05 21.05204 Tundla ad11.0311.0509.5009.55... ... 10.3010.32... ...221 Firozabad d 11.28 10.13 ... ... ... ...241 Shikohabad d ... 10.38 ... ... ... ...296 Etawah d 12.18 11.23 ... ... 11.43 ... ... 23.38 23.38435 Kanpur ad14.4514.5513.4513.5513.3513.4517.5518.0013.2513.3518.2518.3001.1001.1501.1001.1501.3001.3501.3001.35GOY00.5501.00
9.4003.2503.3017.3517.4017.3517.40511 Fatehpur d 15.53 15.05 ... ... 14.30 ... ...PrayagrajRambag15.4002.40 02.40 Unchahar 12.25Prayag 14.2014.22627
Prayagrajad17.4017.4517.0517.1016.2516.3020.2520.3016.0516.15......03.4503.5003.4503.5004.45 04.4504.0004.05
PrayagrajSangamArr. 14.4506.2019.4519.4719.5019.52764
Varanasiad 02.3502.45 02.5503.05 18.0018.05717 Mirzapur d 19.18 18.27 ... ... ... ... ...780Pt. Deen Dayal Upadhyaya Jn.ad21.2321.3320.3820.4819.2319.3303.3303.4323.2023.3018.4018.5023.3523.4503.5504.0506.1006.2006.1006.2018.5019.00 07.0507.15 22.0222.1222.0222.12 881 Sasaram d 22.02 ... 00.38 07.27 ...898 Dehri-on-Sone d 22.20 ... 00.52 07.42 ...984
Gayaad23.3023.3522.0022.0502.55 09.3508.3508.401135 Parasnath d 02.01 ... ...1153Netaji Subhash Chandra Bose Gomohd 02.23 ... 11.301182Dhanbadad03.1703.2201.1501.20875 Buxar d 22.47 05.13 19.56 00.48 05.24 20.27 08.20 23.13 23.13943 Ara d 23.32 06.06 20.42 01.32 06.16 21.26 09.04 23.56 23.56983Danapurad00.0400.06 06.4006.4221.2521.27......
07.1522.1822.20 ...... ... ...
Patliputra Jn.ad 21.4521.55 19.2019.25992
Patnaad00.4000.50 07.0507.15 02.3002.40 22.4522.5520.0510.0010.1020.4519.5520.0500.5501.0500.5501.05995
Rajendranagar(T) ad...... 07.2307.25 ...... ...... 20.1220.14...... ... ... ... ...1081 Mokama d 02.27 04.12 00.16 21.36 ... ... ... 02.00 02.00
12.45
1115 Kiul d 05.45 00.47 22.12 12.04 ... 22.12 02.30 02.30 13.551169 Jhajha d 02.00 23.45 14.00 ... 23.45 04.10 04.10 15.401214 Jasidih d 02.37 00.19 14.34 ... 00.19 04.42 04.42 16.54
07.10
1243 Madhupur d 03.04 00.46 15.01 ... 00.46 05.25 05.25 17.39 07.371299 Chittaranjan d 03.44 ... 15.52 ... ... 18.44 ...1242 Asansol ad04.3104.3602.2502.30 04.1804.23 01.5602.0116.4216.47 01.5602.0101.5602.01 20.1520.3508.5708.59 1283 Durgapur d 05.08 ... 04.55 02.32 ... ... 02.33 21.38 09.401161 Jamalpur d 06.461214
Bhagalpur a 08.15
1347 Barddhaman d 06.26 ... 06.00 ... 18.28 ... ... 23.46 10.461412 Bandel d ... 00.53 1435Dankunid 11.531457
Kolkata a 05.15 21.05 05.15
Shalimar a 05.45
1459 Sealdah a1453
Howrah a 08.05 06.00 07.40 03.00
Days of arrival at destination station Daily Daily Th,Su Daily Daily Daily Daily Daily Su W Daily M, W, Th, SaTu, F, SuM,Th,-SaSa Daily W,F,Su Tu W,F,M Tu Th Daily SaTo Table No. 18 67 18 87A 40Prayagraj
60TAG-22

In [1]:
import tabula
import os

In [2]:
# read PDF file
tables = tabula.read_pdf("../T_1.pdf", pages="all")

In [3]:
# save them in a folder
folder_name = "tables"
if not os.path.isdir(folder_name):
    os.mkdir(folder_name)
# iterate over extracted tables and export as excel individually
for i, table in enumerate(tables, start=1):
    table.to_excel(os.path.join(folder_name, f"table_{i}.xlsx"), index=False)

In [5]:
tables[0]

,Unnamed: 0,Delhi,Kalka,Barm-,New,New.1,Anand,Anand.1,Anand.2,Anand.3,...,Patna,Veerangna,Kanpur,Patna.1,Ghazi-,Anand.5,Anand.6,Anand.7,Moka-,Jasi-
0,NaN,Alipur-,Howrah,er,Delhi,Delhi,Vihar,Vihar (T),Vihar (T),Vihar,...,Kol-,Laxmi Bai,Prayagraj,Shali-,pur,Vihar (T,Vihar (T),Vihar (T),ma,dih-SM-
1,NaN,duar Jn.,Netaji,How-,Rajgir,Gaya,(T) Ka-,Bhagal-,Danapur,(T),...,kata,Kolkata,sangam,mar,city,Prayag-,Mad-,Madhupur,How-,VT
2,TRAIN NAME,Sikkim,Ex-,rah,Shram-,Ma-,makhya,pur,Jan,Gaya,...,Garib,Pratham,Express,Duron-,Kolkata,raj,hupur,Baba Vaidy-,rah,Bengal-
3,NaN,Mahan-,press,Ex-,jeevi,habodhi,North,Vikram,Sad-,Garib,...,Rath,Swatantrata,NaN,to,Expre,Hum-,Hum-,anath Dham,Ex-,uru Ex-
4,NaN,anda,NaN,press,Express,Ex-,East Ex-,Shila,haran,rath Ex-,...,Ex-,Sangram,NaN,Ex-,ss (Via,safar,safar,Deoghar,press,press
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,1453 Howrah a,NaN,08.05,06.00,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.00,NaN
103,Days of arrival at,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,"M,Th,-",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,NaN,Daily,Daily,"Th,Su",Daily,Daily,Daily,Daily,Daily,Su,...,NaN,Sa,Daily,"W,F,Su",Tu,"W,F,M",Tu,Th,Daily,Sa
105,destination station,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Sa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,To Table No.,18,NaN,NaN,67,NaN,18,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40

In [6]:
tables[0][0]

KeyError: 0

In [9]:
tables[0].Bikaner[6]

'12404'

In [8]:
tables[0]['Train Number']

KeyError: 'Train Number'